/*
 * dateserver.c - remote procedures; called by server stub.
 */

#include	"Date1_defs.h"	/* this file is generated by xnscourier */

/*
 * Return the binary date and time.
 */

BinDateResults
BinDate(conn, bdtptr)
CourierConnection	*conn;		/* ignored */
char			*bdtptr;	/* ignored */
{
	BinDateResults	result;
	long		time();			/* Unix function */

	result.bindate = time((long *) 0);

	return(result);
}

/*
 * Convert a binary time and return a human readable string.
 */

StrDateResults
StrDate(conn, bdtptr, bintime)
CourierConnection	*conn;		/* ignored */
char			*bdtptr;	/* ignored */
long			bintime;
{
	StrDateResults	result;
	char		*ctime();		/* Unix function */

	result.strdate = ctime(&bintime);	/* convert to local time */

	return(result);
}
